name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  firebase_auth: 4.19.4
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  go_router: ^13.2.3
  flutter_svg: ^2.0.10+1
  flutter_secure_storage: ^9.0.0
  animate_do: ^3.3.4
  gap: ^3.0.1
  preload_page_view: ^0.2.0
  flutter_bloc: ^8.1.5
  flex_color_scheme: ^7.3.1
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  flutter_localization: ^0.2.0
  geolocator: ^11.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/images/visa_card.png
    - assets/images/master_card.png

  fonts:
  - family: "Poppins"
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 400
      - asset: assets/fonts/Poppins-ThinItalic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
